"""review status and error message

Revision ID: 38b7745932c4
Revises: c7e4e551eb06
Create Date: 2026-09-28 15:42:47.470064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b7745932c4'
down_revision = 'c7e4e551eb06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Manually adjusted: autogenerate emitted status as NOT NULL with no
    # default, which would fail outright against a real Postgres table
    # that already has rows (existing rows would have no value to satisfy
    # the constraint). server_default backfills every pre-existing row as
    # 'complete' — the only status that makes sense retroactively, since
    # every row that already exists here was created (under the pre-this-
    # phase code) by a review that had ALREADY finished successfully by
    # the time its row was ever inserted; the model's own Python-side
    # default ('pending') is for newly-created rows going forward, applied
    # by SQLAlchemy at insert time, not by this column default.
    op.add_column(
        'session_note_reviews',
        sa.Column('status', sa.String(length=24), nullable=False, server_default='complete'),
    )
    op.add_column('session_note_reviews', sa.Column('error_message', sa.Text(), nullable=True))
    # batch_alter_table, not a bare op.alter_column: sqlite (this backend's
    # own test-suite dialect) has no ALTER COLUMN at all — batch mode
    # rebuilds the table under the hood, which also works unchanged against
    # real Postgres. Same reasoning as every other portable, dialect-
    # generic choice in this schema (see app/db/models.py's own docstring).
    with op.batch_alter_table('session_note_reviews') as batch_op:
        batch_op.alter_column('audit_result', existing_type=sa.VARCHAR(length=16), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_note_reviews') as batch_op:
        batch_op.alter_column('audit_result', existing_type=sa.VARCHAR(length=16), nullable=False)
    op.drop_column('session_note_reviews', 'error_message')
    op.drop_column('session_note_reviews', 'status')
    # ### end Alembic commands ###
