"""initial schema

Revision ID: b2d86a250466
Revises: 
Create Date: 2026-09-28 13:20:17.339944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d86a250466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('global_key', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_global_key'), 'people', ['global_key'], unique=True)
    op.create_table('session_note_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('original_pdf_path', sa.String(length=1024), nullable=False),
    sa.Column('classification_result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('service_code', sa.String(length=16), nullable=True),
    sa.Column('date_of_service', sa.Date(), nullable=True),
    sa.Column('appendix', sa.String(length=16), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('classification_confidence', sa.String(length=16), nullable=False),
    sa.Column('classification_note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['session_note_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_note_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_document_id', sa.String(length=36), nullable=False),
    sa.Column('extraction', sa.JSON(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('audit_result', sa.String(length=16), nullable=False),
    sa.Column('api_calls_used', sa.Integer(), nullable=False),
    sa.Column('spend_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_document_id'], ['person_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('model_status', sa.String(length=32), nullable=True),
    sa.Column('model_finding', sa.Text(), nullable=True),
    sa.Column('model_evidence', sa.JSON(), nullable=True),
    sa.Column('model_page', sa.JSON(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('final_status', sa.String(length=32), nullable=False),
    sa.Column('final_finding', sa.Text(), nullable=True),
    sa.Column('final_pages', sa.JSON(), nullable=True),
    sa.Column('overridden_by', sa.String(length=255), nullable=True),
    sa.Column('overridden_at', sa.DateTime(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['session_note_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_results')
    op.drop_table('session_note_reviews')
    op.drop_table('person_documents')
    op.drop_table('session_note_batches')
    op.drop_index(op.f('ix_people_global_key'), table_name='people')
    op.drop_table('people')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
