"""score reviewer document summary fields

Revision ID: c7e4e551eb06
Revises: b2d86a250466
Create Date: 2026-09-28 14:09:34.469566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e4e551eb06'
down_revision = 'b2d86a250466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewers_name'), 'reviewers', ['name'], unique=True)
    op.add_column('session_note_reviews', sa.Column('provider_name', sa.String(length=255), nullable=True))
    op.add_column('session_note_reviews', sa.Column('bcba_name', sa.String(length=255), nullable=True))
    op.add_column('session_note_reviews', sa.Column('session_start_time', sa.String(length=64), nullable=True))
    op.add_column('session_note_reviews', sa.Column('session_end_time', sa.String(length=64), nullable=True))
    op.add_column('session_note_reviews', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_note_reviews', 'score')
    op.drop_column('session_note_reviews', 'session_end_time')
    op.drop_column('session_note_reviews', 'session_start_time')
    op.drop_column('session_note_reviews', 'bcba_name')
    op.drop_column('session_note_reviews', 'provider_name')
    op.drop_index(op.f('ix_reviewers_name'), table_name='reviewers')
    op.drop_table('reviewers')
    # ### end Alembic commands ###
