/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AuditsIndexRouteImport } from './routes/audits.index'
import { Route as AuditsAuditIdRouteImport } from './routes/audits.$auditId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIndexRoute = AuditsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditsRoute,
} as any)
const AuditsAuditIdRoute = AuditsAuditIdRouteImport.update({
  id: '/$auditId',
  path: '/$auditId',
  getParentRoute: () => AuditsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRouteWithChildren
  '/people': typeof PeopleRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/audits/$auditId': typeof AuditsAuditIdRoute
  '/audits/': typeof AuditsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/people': typeof PeopleRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/audits/$auditId': typeof AuditsAuditIdRoute
  '/audits': typeof AuditsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audits': typeof AuditsRouteWithChildren
  '/people': typeof PeopleRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/audits/$auditId': typeof AuditsAuditIdRoute
  '/audits/': typeof AuditsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audits'
    | '/people'
    | '/rules'
    | '/settings'
    | '/upload'
    | '/audits/$auditId'
    | '/audits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/people'
    | '/rules'
    | '/settings'
    | '/upload'
    | '/audits/$auditId'
    | '/audits'
  id:
    | '__root__'
    | '/'
    | '/audits'
    | '/people'
    | '/rules'
    | '/settings'
    | '/upload'
    | '/audits/$auditId'
    | '/audits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditsRoute: typeof AuditsRouteWithChildren
  PeopleRoute: typeof PeopleRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/': {
      id: '/audits/'
      path: '/'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuditsIndexRouteImport
      parentRoute: typeof AuditsRoute
    }
    '/audits/$auditId': {
      id: '/audits/$auditId'
      path: '/$auditId'
      fullPath: '/audits/$auditId'
      preLoaderRoute: typeof AuditsAuditIdRouteImport
      parentRoute: typeof AuditsRoute
    }
  }
}

interface AuditsRouteChildren {
  AuditsAuditIdRoute: typeof AuditsAuditIdRoute
  AuditsIndexRoute: typeof AuditsIndexRoute
}

const AuditsRouteChildren: AuditsRouteChildren = {
  AuditsAuditIdRoute: AuditsAuditIdRoute,
  AuditsIndexRoute: AuditsIndexRoute,
}

const AuditsRouteWithChildren =
  AuditsRoute._addFileChildren(AuditsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditsRoute: AuditsRouteWithChildren,
  PeopleRoute: PeopleRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
