/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UploadHistoryRouteImport } from './routes/upload-history'
import { Route as AuditsIndexRouteImport } from './routes/audits.index'
import { Route as AuditsAuditIdRouteImport } from './routes/audits.$auditId'
import { Route as AuditsAuditIdIndexRouteImport } from './routes/audits.$auditId.index'
import { Route as AuditsAuditIdExtractionRouteImport } from './routes/audits.$auditId.extraction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadHistoryRoute = UploadHistoryRouteImport.update({
  id: '/upload-history',
  path: '/upload-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIndexRoute = AuditsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditsRoute,
} as any)
const AuditsAuditIdRoute = AuditsAuditIdRouteImport.update({
  id: '/$auditId',
  path: '/$auditId',
  getParentRoute: () => AuditsRoute,
} as any)
const AuditsAuditIdIndexRoute = AuditsAuditIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditsAuditIdRoute,
} as any)
const AuditsAuditIdExtractionRoute = AuditsAuditIdExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => AuditsAuditIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/upload-history': typeof UploadHistoryRoute
  '/audits/$auditId': typeof AuditsAuditIdRouteWithChildren
  '/audits/': typeof AuditsIndexRoute
  '/audits/$auditId/extraction': typeof AuditsAuditIdExtractionRoute
  '/audits/$auditId/': typeof AuditsAuditIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/upload-history': typeof UploadHistoryRoute
  '/audits': typeof AuditsIndexRoute
  '/audits/$auditId/extraction': typeof AuditsAuditIdExtractionRoute
  '/audits/$auditId': typeof AuditsAuditIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audits': typeof AuditsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/upload-history': typeof UploadHistoryRoute
  '/audits/$auditId': typeof AuditsAuditIdRouteWithChildren
  '/audits/': typeof AuditsIndexRoute
  '/audits/$auditId/extraction': typeof AuditsAuditIdExtractionRoute
  '/audits/$auditId/': typeof AuditsAuditIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audits'
    | '/rules'
    | '/settings'
    | '/upload'
    | '/upload-history'
    | '/audits/$auditId'
    | '/audits/'
    | '/audits/$auditId/extraction'
    | '/audits/$auditId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rules'
    | '/settings'
    | '/upload'
    | '/upload-history'
    | '/audits'
    | '/audits/$auditId/extraction'
    | '/audits/$auditId'
  id:
    | '__root__'
    | '/'
    | '/audits'
    | '/rules'
    | '/settings'
    | '/upload'
    | '/upload-history'
    | '/audits/$auditId'
    | '/audits/'
    | '/audits/$auditId/extraction'
    | '/audits/$auditId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditsRoute: typeof AuditsRouteWithChildren
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  UploadHistoryRoute: typeof UploadHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-history': {
      id: '/upload-history'
      path: '/upload-history'
      fullPath: '/upload-history'
      preLoaderRoute: typeof UploadHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/': {
      id: '/audits/'
      path: '/'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuditsIndexRouteImport
      parentRoute: typeof AuditsRoute
    }
    '/audits/$auditId': {
      id: '/audits/$auditId'
      path: '/$auditId'
      fullPath: '/audits/$auditId'
      preLoaderRoute: typeof AuditsAuditIdRouteImport
      parentRoute: typeof AuditsRoute
    }
    '/audits/$auditId/': {
      id: '/audits/$auditId/'
      path: '/'
      fullPath: '/audits/$auditId/'
      preLoaderRoute: typeof AuditsAuditIdIndexRouteImport
      parentRoute: typeof AuditsAuditIdRoute
    }
    '/audits/$auditId/extraction': {
      id: '/audits/$auditId/extraction'
      path: '/extraction'
      fullPath: '/audits/$auditId/extraction'
      preLoaderRoute: typeof AuditsAuditIdExtractionRouteImport
      parentRoute: typeof AuditsAuditIdRoute
    }
  }
}

interface AuditsAuditIdRouteChildren {
  AuditsAuditIdExtractionRoute: typeof AuditsAuditIdExtractionRoute
  AuditsAuditIdIndexRoute: typeof AuditsAuditIdIndexRoute
}

const AuditsAuditIdRouteChildren: AuditsAuditIdRouteChildren = {
  AuditsAuditIdExtractionRoute: AuditsAuditIdExtractionRoute,
  AuditsAuditIdIndexRoute: AuditsAuditIdIndexRoute,
}

const AuditsAuditIdRouteWithChildren = AuditsAuditIdRoute._addFileChildren(
  AuditsAuditIdRouteChildren,
)

interface AuditsRouteChildren {
  AuditsAuditIdRoute: typeof AuditsAuditIdRouteWithChildren
  AuditsIndexRoute: typeof AuditsIndexRoute
}

const AuditsRouteChildren: AuditsRouteChildren = {
  AuditsAuditIdRoute: AuditsAuditIdRouteWithChildren,
  AuditsIndexRoute: AuditsIndexRoute,
}

const AuditsRouteWithChildren =
  AuditsRoute._addFileChildren(AuditsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditsRoute: AuditsRouteWithChildren,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  UploadHistoryRoute: UploadHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
